tutorialsIndex_pt = {"Básico", "Sistemas Básicos", "Sistemas Avançados", "NPCs", "Moedas", "Doação"}

tutorialsInfo_pt = {
-- Básico --
    {
        {name = "01. Introdução", text = "PokeFANS é um servidor com uma base única e sistemas exclusivos.\n\nBuscamos trazer sempre inovação e diversão para todos nossos jogadores.", img = "imgs/basic/b1"}, 
        {name = "02. Controlar Objetos", text = "Para controlar itens, basta clicar e segurar o botão esquerdo do mouse pressionado e arrastá-lo para onde quiser.", img = "imgs/basic/b2"}, 
        {name = "03. Interface", text = "Possuimos uma interface única e integrada para os jogadores, nela você tem acesso à todos os comandos necessários para sua jogatina.", img = "imgs/basic/b3"}, 
        {name = "04. Order", text = "Com o order, você pode controlar seu pokémon em batalha, escolhendo onde seu pokémon deve se posicionar.\n\nVocê pode usar o order clicando no ícone ou com o atalho 'BOTÃO DO MEIO DO MOUSE'.\n\nAlguns pokémons possuem habilidades que necessitam do uso do ORDER para serem ativadas, como Fly, Ride, Rock Smash, Cut, entre outras.\n\nVocê pode conferir mais sobre estas habilidades na aba 'habilidades'.", img = "imgs/basic/b4"},		       
        {name = "05. Pokédex", text = "Com a pokédex, você pode checar informações dos pokémons, como status, habilidades, evoluções, moveset, etc...\n\nToda vez que você descobrir um pokémon novo você ganhará experiência por isso.\n\nVocê pode usar a pokédex clicando no ícone e depois clicando em um pokémon, ou usando o atalho 'CTRL+D' e em seguida clicar em um pokémon.", img = "imgs/basic/b5"}, 
        {name = "06. Mochila", text = "A mochila é onde todos os seus itens, pokémons e espólios ficam armazenados.\n\nPara abrir a mochila, basta clicar no ícone ou usar o atalho 'CTRL+I'.", img = "imgs/basic/b6"},       
		{name = "07. Pesca", text = "Com a vara de pesca você pescar pokémons selvagens em qualquer fonte de água, sendo um ótimo método de up.\n\nPara pescar, basta clicar no ícone e depois clicar em um corpo de água, ou utilizar o atalho 'CTRL+Z'.\n\nVocê pode alternar entre suas varas de pesca utilizando o atalho 'CTRL+X', porém, você precisa ter liberado as outras varas antes.", img = "imgs/basic/b7"},        
        {name = "08. Evolução", text = "O ícone de evolução permite que você evolua seus pokémons, desde que eles evoluam por level ou amor.\n\nPara evoluir um pokémon basta clicar no ícone e depois em seu pokémon que deseja evoluir, ou utilizar o atalho 'CTRL+E'.", img = "imgs/basic/b8"},
        {name = "09. Carteira", text = "A carteira mostra quanto dinheiro você tem salvo no banco e quantos tokens seu personagem tem.\n\nVocê pode conferir mais sobre os tokens na aba 'moedas'.", img = "imgs/basic/b9"},
        {name = "10. Caixa de Insígnia", text = "A caixa de insígnia serve para você checar quais insígnias seu personagem já conquistou.\n\nCada insígnia aumenta o limite de diferença de level em 5 níveis.\n\nVocê pode conferir mais sobre o sistema de níveis na aba 'sistemas'.", img = "imgs/basic/b10"},
        {name = "11. PokéBAR", text = "A pokébar é uma interface para facilitar sua jogatina, você pode escolher rapidamente qual pokémon deseja soltar com apenas um clique. Basta clicar no ícone do pokémon desejado.\n\nVocê pode soltar seus pokémons com os atalhos 'CTRL+F1', 'CTRL+F2', 'CTRL+F3', 'CTRL+F4', 'CTRL+F5' e 'CTRL+F6', sendo a ordem dos ícones.", img = "imgs/basic/b11"},
		{name = "12. MoveBAR", text = "A movebar é uma interface para facilitar sua jogatina, você pode escolher rapidamente qual ataque deseja usar com apenas um clique. Basta clicar no ícone do ataque desejado.\n\nVocê pode atacar utilizando as teclas de atalho 'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11' e 'F12', sendo a ordem dos ícones.", img = "imgs/basic/b12"},
		{name = "13. Minimapa", text = "O minimapa mostra sua localização atual.\n\nVocê pode dar zoom-in e zoom-out utilizando a roleta do mouse.", img = "imgs/basic/b13"},  
        {name = "14. Conversando com NPC", text = "Você pode iniciar uma conversa com um NPC ao clicar em nele com o botão esquerdo do mouse.\n\nVocê pode fazer escolhas de diálogo clicando em cima do texto azul, caso o NPC possua escolhas.", img = "imgs/basic/b14"},
    },
-- Sistemas Basicos--
    {
        {name = "01. Autoloot e Loot Comum", text = "O autoloot é ativado automaticamente quando voce cria seu personagem. Todo o loot dropado pelos pokémons selvagens irão diretamente para seu inventario. Para desativar o autoloot basta digitar !autoloot.\n\nO loot comum é o loot que todo pokémon de certa tipagem dropa, por exemplo, todo pokémon de água sempre vai ter a chance de dropar Water Gem, Water Pendant, etc...\nEsses loots não aparecem na mensagem de loot, porém, são pegos no autoloot.", img = "imgs/sistemabasic/sb1"},
        {name = "02. Captura", text = "Para capturar um pokémon, voce deve primeiro derrota-lo em combate.\nApós derrotado, você pode jogar uma poké bola nele e tentar a captura.\nPara utilizar uma pokébola basta clicar com o botão direito nela e depois com o botão esquerdo no pokémon derrotado.\nSe a pokébola piscar verde no final, você capturou.\nSe a pokébola piscar vermelha no final, você não capturou.\n\nEm nosso servidor possuimos diferentes tipos de poké bolas.\nPokeball - Possui 1.0x de captura.\nGreatball - Possui 1.5x de captura.\nUltraball - Possui 2.0x de captura.\nMasterball - Sempre captura o pokémon.\nParkball - Possui 5.0x de captura, só funciona no PokePARK.\nSaffariball - Possui 1.5x de captura, só funciona no Saffari.\nHeavyball - Aumenta a chance de captura de acordo com o peso do pokémon derrotado.\nDuskball - Possui 3.5x de captura, só funciona a noite.\nLoveball - Possui 4.0x de captura, só funciona no mesmo pokémon que você está utilizando.\nNetball - Possui 3.5x de captura, só funciona em pokémons inseto e água.\nPremierball - Uma pokebola especial que possui 1.0x de captura, porém adiciona uma aura ao pokémon quando captura.\n\nAs pokébolas normais, como Pokeball, Greatball e Ultraball podem ser compradas no NPC Mark, no trading center.\nAs pokébolas especiais, como Heavyball, Duskball, Loveball, Netball e Premierball podem ser adquiridas com o NPC Token Collector no trading center.\nAs pokébolas Saffari e Parkball são de uso exclusivo dos locais.\nA pokébola mais forte do jogo, Masterball, deve ser obtida por meio de quests e desafios.", img = "imgs/sistemabasic/sb2"},
        {name = "03. Level e EXP Share.", text = "Em nosso servidor, os pokémons possuem nível e isso influencia diretamente o combate. Seu pokémon precisa de nível para evoluir, usar ataques, etc...\nO pokémon que você utilizar para abatar o pokémon selvagem será o que receberá experiência. Caso você esteja com um EXP Share em algum outro pokémon, ele também receberá experiência, mesmo não participando do combate.\n\nEXP Share\nO exp share pode ser obtido no NPC Token Collector, no trading center. Para dar o exp share a um pokémon, basta clicar com o botao direito no exp share e o botao esquerdo no pokémon que deseja.", img = "imgs/sistemabasic/sb3"},
        {name = "04. Fly, ride e surf", text = "Se o seu pokémon possuir uma dessas habilidades, você poderá utiliza-las para ter uma melhor mobilidade.\n\nCom o Fly, basta utilizar o order em você mesmo com o pokémon solto, que ele irá até você e iniciará o fly. Utilize PageUp para subir um andar e PageDown para descer um andar. Para sair do fly basta dar order em você mesmo novamente.\n\nCom o ride, basta utilizar o order em você mesmo para montar e desmontar.\n\nCom o surf, basta andar em um corpo de água com o pokémon solto que você começa a surfar.", img = "imgs/sistemabasic/sb4"},
    },		
-- Sistemas Avançados --
    {
        {name = "01. TM System",      text = "O sistema de TM permite que você crie o pokémon perfeito pro seu estilo de jogo. Você utiliza o item 'clean disk' para ensinar TMs especificos para o seu pokémon. Para abrir a interface de TM basta segurar CTRL e clicar em cima do seu pokémon, em seguida clicar em 'TM System'.\n\nCada TM tem seu próprio custo, cooldown, nível necessário e pokémons que podem aprender, então nem todos os pokémons podem aprender todos os TMs.", img = "imgs/sistemasadv/sa1"},
        {name = "02. EV System",     text = "O sistema de EV permite que voce balanceie melhor o seu pokémon, de acordo com sua necessidade. Cada pokémon pode receber até 300 pontos de EV e pode colocar até 150 pontos em cada status.\nO status HP aumenta a vida em 10 para cada ponto gasto, o status ATK aumenta o ataque em 1 para cada ponto gasto e o status DEF aumenta a defesa em 1 para cada ponto gasto. Para receber pontos basta abater os pokémons selvagens que você recebe EV Points.\n\nPara abrir a interface de EV basta segurar CTRL e clicar em cima do seu pokémon, em seguida clicar em 'EV System'.", img = "imgs/sistemasadv/sa2"},
        {name = "03. Dungeon System",         text = "Em nosso servidor, possuimos um sistema de Dungeon instanciado, onde você pode entrar e desafiar os pokémons lendários.\nPara entrar na dungeon, basta acessar o dispositivo no último andar do centro pokémon.", img = "imgs/sistemasadv/sa3"},
        {name = "04. Tera System", 			text = "Pokémon Tera, Pokémon Terastal ou Tera System, é quando um pokémon selvagem spawna com uma tipagem TERA. Pokémons com a tipagem TERA ignoram a tipagem natural do pokémon e possuem apenas a tipagem TERA.\nUm pokémon TERA de Fogo, aplicará dano e receberá dano como se fosse do tipo Fogo originalmente. Adicionalmente, caso o pokémon utilize um ataque da mesma tipagem que seu TERA, ele causará STAB equivalente a 2.0x, enquanto um pokémon sem TERA causará 2.0x.\n\nPokémons TERA spawnam naturalmente pelo mundo e possuem uma aura única dada à eles, o que os diferencia totalmente dos outros pokémons comuns. Pokémons teras são extremamente raros e valiosos.", img = "imgs/sistemasadv/sa4"},
        {name = "05. Smeargle System",         text = "O Smeargle é um pokémon único comparado à todos os outros. Smeargle pode aprender ataques de outros pokémons, utilizando o seu ataque 'Sketch', cada smeargle possui 8 sketches que podem copiar 8 ataques diferentes.\n\nPara copiar um ataque de um pokémon, use o order no smeargle, para desbloquear ele. Depois, de target no pokemon que queira copiar e use o ataque da mesma numeração do ataque que voce quer copiar.\n\nExemplo: Se eu desejo copiar o ataque M4 de um pokémon, devo usar o Sketch 4.", img = "imgs/sistemasadv/sa5"},
        {name = "06. Ditto System",      text = "Ditto é outro pokémon único, ele consegue copiar qualquer pokémon, desde que não seja lendário. Ditto copia os status, aparência e ataques do pokémon, sendo um ótimo coringa no time. Capturar um Ditto não é uma tarefa muito fácil, ele se esconde pelo mundo se disfarçando de outros pokémons, então você só vai saber que é um ditto quando derrotar o pokémon e uma gosma rosa aparecer no chão!\n\nPara copiar um pokémon com seu ditto, basta utilizar Order no pokémon que deseja copiar e para voltar ao normal, basta usar order no ditto.", img = "imgs/sistemasadv/sa6"},
        {name = "07. Computer System",         text = "Se voce adquirir um computador pessoal com o NPC Token Collector no trading center, você pode fazer uma variedade de coisas no seu computador (dentro de casa).\nPoké Food - Delivery de comida pra você, as melhores comidas do mercado na palma da sua mão.\nRemove Held - Permite que você remova um held do seu pokémon, muito útil se você farma itens com 'Pickup' e 'PayDay'.\nRemove Exp Share - Permite remover o expshare de algum pokémon.\nRotom - Permite mudar a forma do Rotom.\nDeoxys - Permite mudar a forma do Deoxys.", img = "imgs/sistemasadv/sa7"},
        {name = "08. Held System",         text = "Helds aumentam status específicos ou causam bonus em alguns efeitos. Helds podem ser adquiridos com o NPC Token Collector no trading center.\nOs helds possuem dois tiers, sendo um para pokémons de nível 50- e outro para pokémons de nível 50+.\n\nHeld Attack - aumenta o ataque do pokémon.\nHeld Defense - aumenta a defesa do pokémon.\nHeld Experience - aumenta a experiencia que o pokemon recebe.\nHeld Burn - aumenta o dano do status burn causado pelo pokémon.\nHeld Poison - aumenta o dano do status poison causado pelo pokémon.\nHeld Vitality - aumenta a vida do pokémon.\nHeld Wing - aumenta a velocidade de voo do pokémon.\nHeld Cure - chance de curar condições do pokémon a cada segundo.", img = "imgs/sistemasadv/sa8"},
        {name = "09. Reborn System",        text = "O sistema de Reborn, serve para você voltar ao nível um e poder refazer algumas quests. Algumas dungeons e sistemas tem um requisito mínimo de reborns necessários.\nPara rebornar basta atingir o nível 1000 e digitar /reborn .\nO limite máximo de reborns é 10.", img = "imgs/sistemasadv/sa9"},
        {name = "10. PokePARK",text = "PokePARK é um evento global que acontece toda terça, quinta, sábado e domingo, as 11:00, 16:00 e 21:00.\nPara acessar o PokePARK voce deve ter um PokePARK ticket, que pode ser obtido no shop do jogo, por quests ou trade.\n\nAo entrar no PokePARK, voce receberá 50 parkballs, são pokébolas com o multiplicador de cacch altíssimos, tornando o catch muito fácil. Porém, para ao capturar um pokémon no poképark, você não fica com ele, e sim, ganha pontos.\nEsses pontos podem ser utilizados para comprar os pokémons do PokePARK, caso voce os tenha capturado.\nA entrada do PokePARK fica à esquerda do centro pokémon de Port Harbor, utilize !teleport port harbor com algum pokémon com teleport para ir até lá.", img = "imgs/sistemasadv/sa10"},
        {name = "11. Saffari Zone",              text = "A Saffari Zone é uma área artificial com diversos pastos com vários pokémons. Quando você entra em um pasto, ninguém mais pode entrar até você sair. O saffari tem uma variedade muito grande de pastos e pokémons pokémons exclusivos. Para entrar no Saffari, basta ir a port harbor com o teleport (!teleport port harbor) e ir a direita do centro pokémon. Para entrar você precisará de 100 tokens.", img = "imgs/sistemasadv/sa11"},
        {name = "12. Food System",            text = "As comidas no jogo servem como as potions para pokémons, porém para jogadores. Ao consumir uma comida, você ira regenerar vida a cada segundo, de acordo com a comida utilizada.\n\nDiversos NPCs vendem comida pelo mundo, e caso você possua um computador, pode optar por comprar pelo Poké Food.", img = "imgs/sistemasadv/sa12"},
        {name = "13. Mega System",             text = "Alguns pokémons possuem sua Mega Evolução e podem spawnar evoluidos pelo mapa. Derrotar um desses pokémons te garante a chance de dropar uma mega stone daquele pokémon. Ao utilizar a mega stone em um pokémon seu, ele se tornará mega também, ficando ainda mais forte.", img = "imgs/sistemasadv/sa13"},
        {name = "14. Quest Log",         text = "Quest Log é uma ferramenta de fácil acesso que facilita a vida do jogador. Seu intuito é mostrar as quests disponíveis para o seu nível, sempre atualizando conforme voce upa.\nO Quest log também, mostra as quests que você já finalizou, pra poder lembrar quais foram feitas ou não.\n\nPara acessar o quest log basta clicar no ícone no canto superior direito.", img = "imgs/sistemasadv/sa14"},
		{name = "15. Random Encounter",         text = "Random Encounter permite que você encontre pokémons lendários raramente quando derrota pokémons.\nCaso derrote pokémons de Johto, você tem a chance de encontrar um dos cães lendários.\nCaso derrote pokémons de Hoenn, você tem a chance de encontrar Latios ou Latias.\nCaso derrote pokémons de sinnoh, você tem chance de encontrar Cresselia, caso tenha feito a quest de liberação.", img = "imgs/sistemasadv/sa15"},
	},	

-- NPCs --
	{
        {name = "01. Nurse",      text = "Presente em todos os centros pokémons, cura seus pokémons.", img = "imgs/npc/n1"},
		{name = "02. Job Manager",      text = "Presente no segundo andar do centro pokémon de saffron, possibilita o jogador aderir uma profissão.", img = "imgs/npc/n2"},
		{name = "03. Eva",      text = "Presente no segundo andar do centro pokémon de saffron, responsável pelo sistema de banco.", img = "imgs/npc/n3"},
		{name = "04. Mark",      text = "Presente no trading center, vende itens essenciais para a jornada de um treinador e compra itens dropados dos pokémons.", img = "imgs/npc/n4"},
		{name = "05. Pokémon Collector",      text = "Presente no trading center, compra pokémons dos jogadores.", img = "imgs/npc/n5"},
		{name = "06. Henry",      text = "Presente no trading center, compra e vende pedras evolutivas.", img = "imgs/npc/n6"},
		{name = "07. Token Collector",      text = "Presente no trading center, troca itens por tokens dos jogadores.", img = "imgs/npc/n7"},
		{name = "08. Architect",      text = "Presente no trading center, vende de decoração para casas.", img = "imgs/npc/n8"},
		{name = "09. NPC Trade",      text = "Espalhados pelo mundo inteiro, estes NPCs irão lhe pedir algo e em troca lhe darão algum prêmio.", img = "imgs/npc/n9"},
		{name = "10. NPC Duel",      text = "Espalhados pelo mundo inteiro, estes NPCs irão duelar com você e caso você vença, irá receber um prêmio.", img = "imgs/npc/n10"},
		{name = "11. Mega Collector",      text = "Presente no trading center, compra mega stones por pack de pé (moeda de doação).", img = "imgs/npc/n11"},
		
 	},	 

-- Moedas --       
	{
        {name = "01. Gold Coin",      text = "A moeda principal do jogo, possuindo 4 variações.\n\nGold Coin: Cada gold coin equivale à 1 gold coin.\nPlatinum Coin: Cada platinum coin equivale a 100 gold coins.\nCrystal Coin: Cada crystal coin equivale a 100 platinum coins, que equivale a 10.000 gold coins.\nQuartz Coin: Cada quartz coin equivale a 100 crystal coin, que equivale a 1.000.000 gold coins.", img = "imgs/base"},
		{name = "02. Token",      text = "O token é uma moeda secundária do jogo, que você recebe ao completar quests, tasks, trials e bosses.\nVocê pode trocar os tokens no NPC Token Collector, no TC.", img = "imgs/base"},
		{name = "03. Park Points",      text = "Moeda utilizada para comprar pokémons e itens do PokePARK. Adquirida ao completar o evento PokePARK.", img = "imgs/base"},
		{name = "04. Pack de Pé",      text = "Pack de Pé ou PP é a moeda de doação do servidor, para cada 1 real doado você recebe 1 pack de pé.\nVocê pode utilizar os packs de pé para comprar itens em nosso shop.", img = "imgs/base"},
 	},	 
	
-- Doação --       
	{
        {name = "01. Introdução à doação",      text = "O servidor é um fã-game, logo, não temos intenções lucrativas. Todas as doações feitas são para ajudar a manter o servidor online.\nCaso você decida doar, será muito apreciado, porém, lembre-se, doe somente se você gostar do jogo e se tiver condições de fazer isso!", img = "imgs/base"},
		{name = "02. Instruções para doar",      text = "Para doar você deve enviar um pix para: \nowatari.zayon@gmail.com\nApós isso, encaminhe um print ou informe ao ADM no discord/ingame para que ele cheque a doação.\nAssim que a doação for constatada, será entregue ao seu depot os packs de pé.", img = "imgs/base"},
 	},	 
}