tutorialsIndex_pt = {"B�sico", "Sistemas B�sicos", "Sistemas Avan�ados", "NPCs", "Moedas", "Doa��o"}

tutorialsInfo_pt = {
-- B�sico --
    {
        {name = "01. Introdu��o", text = "PokeMMO � um servidor com uma base �nica e sistemas exclusivos.\n\nBuscamos trazer sempre inova��o e divers�o para todos nossos jogadores.", img = "imgs/basic/b1"}, 
        {name = "02. Controlar Objetos", text = "Para controlar itens, basta clicar e segurar o bot�o esquerdo do mouse pressionado e arrast�-lo para onde quiser.", img = "imgs/basic/b2"}, 
        {name = "03. Interface", text = "Possuimos uma interface �nica e integrada para os jogadores, nela voc� tem acesso � todos os comandos necess�rios para sua jogatina.", img = "imgs/basic/b3"}, 
        {name = "04. Order", text = "Com o order, voc� pode controlar seu pok�mon em batalha, escolhendo onde seu pok�mon deve se posicionar.\n\nVoc� pode usar o order clicando no �cone ou com o atalho 'BOT�O DO MEIO DO MOUSE'.\n\nAlguns pok�mons possuem habilidades que necessitam do uso do ORDER para serem ativadas, como Fly, Ride, Rock Smash, Cut, entre outras.\n\nVoc� pode conferir mais sobre estas habilidades na aba 'habilidades'.", img = "imgs/basic/b4"},		       
        {name = "05. Pok�dex", text = "Com a pok�dex, voc� pode checar informa��es dos pok�mons, como status, habilidades, evolu��es, moveset, etc...\n\nToda vez que voc� descobrir um pok�mon novo voc� ganhar� experi�ncia por isso.\n\nVoc� pode usar a pok�dex clicando no �cone e depois clicando em um pok�mon, ou usando o atalho 'CTRL+D' e em seguida clicar em um pok�mon.", img = "imgs/basic/b5"}, 
        {name = "06. Mochila", text = "A mochila � onde todos os seus itens, pok�mons e esp�lios ficam armazenados.\n\nPara abrir a mochila, basta clicar no �cone ou usar o atalho 'CTRL+I'.", img = "imgs/basic/b6"},       
		{name = "07. Pesca", text = "Com a vara de pesca voc� pescar pok�mons selvagens em qualquer fonte de �gua, sendo um �timo m�todo de up.\n\nPara pescar, basta clicar no �cone e depois clicar em um corpo de �gua, ou utilizar o atalho 'CTRL+Z'.\n\nVoc� pode alternar entre suas varas de pesca utilizando o atalho 'CTRL+X', por�m, voc� precisa ter liberado as outras varas antes.", img = "imgs/basic/b7"},        
        {name = "08. Evolu��o", text = "O �cone de evolu��o permite que voc� evolua seus pok�mons, desde que eles evoluam por level ou amor.\n\nPara evoluir um pok�mon basta clicar no �cone e depois em seu pok�mon que deseja evoluir, ou utilizar o atalho 'CTRL+E'.", img = "imgs/basic/b8"},
        {name = "09. Carteira", text = "A carteira mostra quanto dinheiro voc� tem salvo no banco e quantos tokens seu personagem tem.\n\nVoc� pode conferir mais sobre os tokens na aba 'moedas'.", img = "imgs/basic/b9"},
        {name = "10. Caixa de Ins�gnia", text = "A caixa de ins�gnia serve para voc� checar quais ins�gnias seu personagem j� conquistou.\n\nCada ins�gnia aumenta o limite de diferen�a de level em 5 n�veis.\n\nVoc� pode conferir mais sobre o sistema de n�veis na aba 'sistemas'.", img = "imgs/basic/b10"},
        {name = "11. Pok�BAR", text = "A pok�bar � uma interface para facilitar sua jogatina, voc� pode escolher rapidamente qual pok�mon deseja soltar com apenas um clique. Basta clicar no �cone do pok�mon desejado.\n\nVoc� pode soltar seus pok�mons com os atalhos 'CTRL+F1', 'CTRL+F2', 'CTRL+F3', 'CTRL+F4', 'CTRL+F5' e 'CTRL+F6', sendo a ordem dos �cones.", img = "imgs/basic/b11"},
		{name = "12. MoveBAR", text = "A movebar � uma interface para facilitar sua jogatina, voc� pode escolher rapidamente qual ataque deseja usar com apenas um clique. Basta clicar no �cone do ataque desejado.\n\nVoc� pode atacar utilizando as teclas de atalho 'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11' e 'F12', sendo a ordem dos �cones.", img = "imgs/basic/b12"},
		{name = "13. Minimapa", text = "O minimapa mostra sua localiza��o atual.\n\nVoc� pode dar zoom-in e zoom-out utilizando a roleta do mouse.", img = "imgs/basic/b13"},  
        {name = "14. Conversando com NPC", text = "Voc� pode iniciar uma conversa com um NPC ao clicar em nele com o bot�o esquerdo do mouse.\n\nVoc� pode fazer escolhas de di�logo clicando em cima do texto azul, caso o NPC possua escolhas.", img = "imgs/basic/b14"},
    },
-- Sistemas Basicos--
    {
        {name = "01. Autoloot e Loot Comum", text = "O autoloot � ativado automaticamente quando voce cria seu personagem. Todo o loot dropado pelos pok�mons selvagens ir�o diretamente para seu inventario. Para desativar o autoloot basta digitar !autoloot.\n\nO loot comum � o loot que todo pok�mon de certa tipagem dropa, por exemplo, todo pok�mon de �gua sempre vai ter a chance de dropar Water Gem, Water Pendant, etc...\nEsses loots n�o aparecem na mensagem de loot, por�m, s�o pegos no autoloot.", img = "imgs/sistemabasic/sb1"},
        {name = "02. Captura", text = "Para capturar um pok�mon, voce deve primeiro derrota-lo em combate.\nAp�s derrotado, voc� pode jogar uma pok� bola nele e tentar a captura.\nPara utilizar uma pok�bola basta clicar com o bot�o direito nela e depois com o bot�o esquerdo no pok�mon derrotado.\nSe a pok�bola piscar verde no final, voc� capturou.\nSe a pok�bola piscar vermelha no final, voc� n�o capturou.\n\nEm nosso servidor possuimos diferentes tipos de pok� bolas.\nPokeball - Possui 1.0x de captura.\nGreatball - Possui 1.5x de captura.\nUltraball - Possui 2.0x de captura.\nMasterball - Sempre captura o pok�mon.\nParkball - Possui 5.0x de captura, s� funciona no PokePARK.\nSaffariball - Possui 1.5x de captura, s� funciona no Saffari.\nHeavyball - Aumenta a chance de captura de acordo com o peso do pok�mon derrotado.\nDuskball - Possui 3.5x de captura, s� funciona a noite.\nLoveball - Possui 4.0x de captura, s� funciona no mesmo pok�mon que voc� est� utilizando.\nNetball - Possui 3.5x de captura, s� funciona em pok�mons inseto e �gua.\nPremierball - Uma pokebola especial que possui 1.0x de captura, por�m adiciona uma aura ao pok�mon quando captura.\n\nAs pok�bolas normais, como Pokeball, Greatball e Ultraball podem ser compradas no NPC Mark, no trading center.\nAs pok�bolas especiais, como Heavyball, Duskball, Loveball, Netball e Premierball podem ser adquiridas com o NPC Token Collector no trading center.\nAs pok�bolas Saffari e Parkball s�o de uso exclusivo dos locais.\nA pok�bola mais forte do jogo, Masterball, deve ser obtida por meio de quests e desafios.", img = "imgs/sistemabasic/sb2"},
        {name = "03. Level e EXP Share.", text = "Em nosso servidor, os pok�mons possuem n�vel e isso influencia diretamente o combate. Seu pok�mon precisa de n�vel para evoluir, usar ataques, etc...\nO pok�mon que voc� utilizar para abatar o pok�mon selvagem ser� o que receber� experi�ncia. Caso voc� esteja com um EXP Share em algum outro pok�mon, ele tamb�m receber� experi�ncia, mesmo n�o participando do combate.\n\nEXP Share\nO exp share pode ser obtido no NPC Token Collector, no trading center. Para dar o exp share a um pok�mon, basta clicar com o botao direito no exp share e o botao esquerdo no pok�mon que deseja.", img = "imgs/sistemabasic/sb3"},
        {name = "04. Fly, ride e surf", text = "Se o seu pok�mon possuir uma dessas habilidades, voc� poder� utiliza-las para ter uma melhor mobilidade.\n\nCom o Fly, basta utilizar o order em voc� mesmo com o pok�mon solto, que ele ir� at� voc� e iniciar� o fly. Utilize PageUp para subir um andar e PageDown para descer um andar. Para sair do fly basta dar order em voc� mesmo novamente.\n\nCom o ride, basta utilizar o order em voc� mesmo para montar e desmontar.\n\nCom o surf, basta andar em um corpo de �gua com o pok�mon solto que voc� come�a a surfar.", img = "imgs/sistemabasic/sb4"},
    },		
-- Sistemas Avan�ados --
    {
        {name = "01. TM System",      text = "O sistema de TM permite que voc� crie o pok�mon perfeito pro seu estilo de jogo. Voc� utiliza o item 'clean disk' para ensinar TMs especificos para o seu pok�mon. Para abrir a interface de TM basta segurar CTRL e clicar em cima do seu pok�mon, em seguida clicar em 'TM System'.\n\nCada TM tem seu pr�prio custo, cooldown, n�vel necess�rio e pok�mons que podem aprender, ent�o nem todos os pok�mons podem aprender todos os TMs.", img = "imgs/sistemasadv/sa1"},
        {name = "02. EV System",     text = "O sistema de EV permite que voce balanceie melhor o seu pok�mon, de acordo com sua necessidade. Cada pok�mon pode receber at� 300 pontos de EV e pode colocar at� 150 pontos em cada status.\nO status HP aumenta a vida em 10 para cada ponto gasto, o status ATK aumenta o ataque em 1 para cada ponto gasto e o status DEF aumenta a defesa em 1 para cada ponto gasto. Para receber pontos basta abater os pok�mons selvagens que voc� recebe EV Points.\n\nPara abrir a interface de EV basta segurar CTRL e clicar em cima do seu pok�mon, em seguida clicar em 'EV System'.", img = "imgs/sistemasadv/sa2"},
        {name = "03. Dungeon System",         text = "Em nosso servidor, possuimos um sistema de Dungeon instanciado, onde voc� pode entrar e desafiar os pok�mons lend�rios.\nPara entrar na dungeon, basta acessar o dispositivo no �ltimo andar do centro pok�mon.", img = "imgs/sistemasadv/sa3"},
        {name = "04. Tera System", 			text = "Pok�mon Tera, Pok�mon Terastal ou Tera System, � quando um pok�mon selvagem spawna com uma tipagem TERA. Pok�mons com a tipagem TERA ignoram a tipagem natural do pok�mon e possuem apenas a tipagem TERA.\nUm pok�mon TERA de Fogo, aplicar� dano e receber� dano como se fosse do tipo Fogo originalmente. Adicionalmente, caso o pok�mon utilize um ataque da mesma tipagem que seu TERA, ele causar� STAB equivalente a 2.0x, enquanto um pok�mon sem TERA causar� 2.0x.\n\nPok�mons TERA spawnam naturalmente pelo mundo e possuem uma aura �nica dada � eles, o que os diferencia totalmente dos outros pok�mons comuns. Pok�mons teras s�o extremamente raros e valiosos.", img = "imgs/sistemasadv/sa4"},
        {name = "05. Smeargle System",         text = "O Smeargle � um pok�mon �nico comparado � todos os outros. Smeargle pode aprender ataques de outros pok�mons, utilizando o seu ataque 'Sketch', cada smeargle possui 8 sketches que podem copiar 8 ataques diferentes.\n\nPara copiar um ataque de um pok�mon, use o order no smeargle, para desbloquear ele. Depois, de target no pokemon que queira copiar e use o ataque da mesma numera��o do ataque que voce quer copiar.\n\nExemplo: Se eu desejo copiar o ataque M4 de um pok�mon, devo usar o Sketch 4.", img = "imgs/sistemasadv/sa5"},
        {name = "06. Ditto System",      text = "Ditto � outro pok�mon �nico, ele consegue copiar qualquer pok�mon, desde que n�o seja lend�rio. Ditto copia os status, apar�ncia e ataques do pok�mon, sendo um �timo coringa no time. Capturar um Ditto n�o � uma tarefa muito f�cil, ele se esconde pelo mundo se disfar�ando de outros pok�mons, ent�o voc� s� vai saber que � um ditto quando derrotar o pok�mon e uma gosma rosa aparecer no ch�o!\n\nPara copiar um pok�mon com seu ditto, basta utilizar Order no pok�mon que deseja copiar e para voltar ao normal, basta usar order no ditto.", img = "imgs/sistemasadv/sa6"},
        {name = "07. Computer System",         text = "Se voce adquirir um computador pessoal com o NPC Token Collector no trading center, voc� pode fazer uma variedade de coisas no seu computador (dentro de casa).\nPok� Food - Delivery de comida pra voc�, as melhores comidas do mercado na palma da sua m�o.\nRemove Held - Permite que voc� remova um held do seu pok�mon, muito �til se voc� farma itens com 'Pickup' e 'PayDay'.\nRemove Exp Share - Permite remover o expshare de algum pok�mon.\nRotom - Permite mudar a forma do Rotom.\nDeoxys - Permite mudar a forma do Deoxys.", img = "imgs/sistemasadv/sa7"},
        {name = "08. Held System",         text = "Helds aumentam status espec�ficos ou causam bonus em alguns efeitos. Helds podem ser adquiridos com o NPC Token Collector no trading center.\nOs helds possuem dois tiers, sendo um para pok�mons de n�vel 50- e outro para pok�mons de n�vel 50+.\n\nHeld Attack - aumenta o ataque do pok�mon.\nHeld Defense - aumenta a defesa do pok�mon.\nHeld Experience - aumenta a experiencia que o pokemon recebe.\nHeld Burn - aumenta o dano do status burn causado pelo pok�mon.\nHeld Poison - aumenta o dano do status poison causado pelo pok�mon.\nHeld Vitality - aumenta a vida do pok�mon.\nHeld Wing - aumenta a velocidade de voo do pok�mon.\nHeld Cure - chance de curar condi��es do pok�mon a cada segundo.", img = "imgs/sistemasadv/sa8"},
        {name = "09. Reborn System",        text = "O sistema de Reborn, serve para voc� voltar ao n�vel um e poder refazer algumas quests. Algumas dungeons e sistemas tem um requisito m�nimo de reborns necess�rios.\nPara rebornar basta atingir o n�vel 1000 e digitar /reborn .\nO limite m�ximo de reborns � 10.", img = "imgs/sistemasadv/sa9"},
        {name = "10. PokePARK",text = "PokePARK � um evento global que acontece toda ter�a, quinta, s�bado e domingo, as 11:00, 16:00 e 21:00.\nPara acessar o PokePARK voce deve ter um PokePARK ticket, que pode ser obtido no shop do jogo, por quests ou trade.\n\nAo entrar no PokePARK, voce receber� 50 parkballs, s�o pok�bolas com o multiplicador de cacch alt�ssimos, tornando o catch muito f�cil. Por�m, para ao capturar um pok�mon no pok�park, voc� n�o fica com ele, e sim, ganha pontos.\nEsses pontos podem ser utilizados para comprar os pok�mons do PokePARK, caso voce os tenha capturado.\nA entrada do PokePARK fica � esquerda do centro pok�mon de Port Harbor, utilize !teleport port harbor com algum pok�mon com teleport para ir at� l�.", img = "imgs/sistemasadv/sa10"},
        {name = "11. Saffari Zone",              text = "A Saffari Zone � uma �rea artificial com diversos pastos com v�rios pok�mons. Quando voc� entra em um pasto, ningu�m mais pode entrar at� voc� sair. O saffari tem uma variedade muito grande de pastos e pok�mons pok�mons exclusivos. Para entrar no Saffari, basta ir a port harbor com o teleport (!teleport port harbor) e ir a direita do centro pok�mon. Para entrar voc� precisar� de 100 tokens.", img = "imgs/sistemasadv/sa11"},
        {name = "12. Food System",            text = "As comidas no jogo servem como as potions para pok�mons, por�m para jogadores. Ao consumir uma comida, voc� ira regenerar vida a cada segundo, de acordo com a comida utilizada.\n\nDiversos NPCs vendem comida pelo mundo, e caso voc� possua um computador, pode optar por comprar pelo Pok� Food.", img = "imgs/sistemasadv/sa12"},
        {name = "13. Mega System",             text = "Alguns pok�mons possuem sua Mega Evolu��o e podem spawnar evoluidos pelo mapa. Derrotar um desses pok�mons te garante a chance de dropar uma mega stone daquele pok�mon. Ao utilizar a mega stone em um pok�mon seu, ele se tornar� mega tamb�m, ficando ainda mais forte.", img = "imgs/sistemasadv/sa13"},
        {name = "14. Quest Log",         text = "Quest Log � uma ferramenta de f�cil acesso que facilita a vida do jogador. Seu intuito � mostrar as quests dispon�veis para o seu n�vel, sempre atualizando conforme voce upa.\nO Quest log tamb�m, mostra as quests que voc� j� finalizou, pra poder lembrar quais foram feitas ou n�o.\n\nPara acessar o quest log basta clicar no �cone no canto superior direito.", img = "imgs/sistemasadv/sa14"},
		{name = "15. Random Encounter",         text = "Random Encounter permite que voc� encontre pok�mons lend�rios raramente quando derrota pok�mons.\nCaso derrote pok�mons de Johto, voc� tem a chance de encontrar um dos c�es lend�rios.\nCaso derrote pok�mons de Hoenn, voc� tem a chance de encontrar Latios ou Latias.\nCaso derrote pok�mons de sinnoh, voc� tem chance de encontrar Cresselia, caso tenha feito a quest de libera��o.", img = "imgs/sistemasadv/sa15"},
	},	

-- NPCs --
	{
        {name = "01. Nurse",      text = "Presente em todos os centros pok�mons, cura seus pok�mons.", img = "imgs/npc/n1"},
		{name = "02. Job Manager",      text = "Presente no segundo andar do centro pok�mon de saffron, possibilita o jogador aderir uma profiss�o.", img = "imgs/npc/n2"},
		{name = "03. Eva",      text = "Presente no segundo andar do centro pok�mon de saffron, respons�vel pelo sistema de banco.", img = "imgs/npc/n3"},
		{name = "04. Mark",      text = "Presente no trading center, vende itens essenciais para a jornada de um treinador e compra itens dropados dos pok�mons.", img = "imgs/npc/n4"},
		{name = "05. Pok�mon Collector",      text = "Presente no trading center, compra pok�mons dos jogadores.", img = "imgs/npc/n5"},
		{name = "06. Henry",      text = "Presente no trading center, compra e vende pedras evolutivas.", img = "imgs/npc/n6"},
		{name = "07. Token Collector",      text = "Presente no trading center, troca itens por tokens dos jogadores.", img = "imgs/npc/n7"},
		{name = "08. Architect",      text = "Presente no trading center, vende de decora��o para casas.", img = "imgs/npc/n8"},
		{name = "09. NPC Trade",      text = "Espalhados pelo mundo inteiro, estes NPCs ir�o lhe pedir algo e em troca lhe dar�o algum pr�mio.", img = "imgs/npc/n9"},
		{name = "10. NPC Duel",      text = "Espalhados pelo mundo inteiro, estes NPCs ir�o duelar com voc� e caso voc� ven�a, ir� receber um pr�mio.", img = "imgs/npc/n10"},
		{name = "11. Mega Collector",      text = "Presente no trading center, compra mega stones por pack de p� (moeda de doa��o).", img = "imgs/npc/n11"},
		
 	},	 

-- Moedas --       
	{
        {name = "01. Gold Coin",      text = "A moeda principal do jogo, possuindo 4 varia��es.\n\nGold Coin: Cada gold coin equivale � 1 gold coin.\nPlatinum Coin: Cada platinum coin equivale a 100 gold coins.\nCrystal Coin: Cada crystal coin equivale a 100 platinum coins, que equivale a 10.000 gold coins.\nQuartz Coin: Cada quartz coin equivale a 100 crystal coin, que equivale a 1.000.000 gold coins.", img = "imgs/base"},
		{name = "02. Token",      text = "O token � uma moeda secund�ria do jogo, que voc� recebe ao completar quests, tasks, trials e bosses.\nVoc� pode trocar os tokens no NPC Token Collector, no TC.", img = "imgs/base"},
		{name = "03. Park Points",      text = "Moeda utilizada para comprar pok�mons e itens do PokePARK. Adquirida ao completar o evento PokePARK.", img = "imgs/base"},
		{name = "04. Pack de P�",      text = "Pack de P� ou PP � a moeda de doa��o do servidor, para cada 1 real doado voc� recebe 1 pack de p�.\nVoc� pode utilizar os packs de p� para comprar itens em nosso shop.", img = "imgs/base"},
 	},	 
	
-- Doa��o --       
	{
        {name = "01. Introdu��o � doa��o",      text = "O servidor � um f�-game, logo, n�o temos inten��es lucrativas. Todas as doa��es feitas s�o para ajudar a manter o servidor online.\nCaso voc� decida doar, ser� muito apreciado, por�m, lembre-se, doe somente se voc� gostar do jogo e se tiver condi��es de fazer isso!", img = "imgs/base"},
		{name = "02. Instru��es para doar",      text = "Para doar voc� deve enviar um pix para: \nowatari.zayon@gmail.com\nAp�s isso, encaminhe um print ou informe ao ADM no discord/ingame para que ele cheque a doa��o.\nAssim que a doa��o for constatada, ser� entregue ao seu depot os packs de p�.", img = "imgs/base"},
 	},	 
}